export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_START = 'FETCH_POSTS_START'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

export const NEW_POST = 'NEW_POST'
export const NEW_POST_START = 'NEW_POST_START'
export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS'
