export const POSTS_FETCH = 'POSTS_FETCH'
export const POSTS_FETCH_START = 'POSTS_FETCH_START'
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS'
export const POSTS_FETCH_FAILED = 'POSTS_FETCH_FAILED'

export const POSTS_CREATE = 'POSTS_CREATE'
export const POSTS_CREATE_START = 'POSTS_CREATE_START'
export const POSTS_CREATE_SUCCESS = 'POSTS_CREATE_SUCCESS'
export const POSTS_CREATE_FAILED = 'POSTS_CREATE_FAILED'
