export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_START = 'USER_LOGIN_START'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const USER_LOGOUT = 'USER_LOGOUT'
